"""v9 (= patches_v8 with the v9 spec: Depreciation Schedule edited + new cells, PO rows 33-35): which cached values change, from a full LibreOffice recalculation of stage 1, limited to the edited cells and the
static downstream set of the edits.

Usage:
  python3 -I patches_v9.py STAGE1_XLSX STAGE1_LO_XLSX SPEC_JSON OUT_PATCH_JSON OUT_NOISE_JSON

- SPEC_JSON (build_v8.py stage1): every edited / new cell (Prod Payroll row 48, Depreciation Schedule rows 128+, PO rows
  20, 21, 33-35).
- Seeds = those cells. deps_v5.downstream() traces every formula cell that can depend on them (static trace of all
  formulas; it stops on INDIRECT / OFFSET / external references, so nothing is missed silently).
- Patch list = every edited / new formula cell + every downstream formula cell whose recalculated value differs from the
  stage 1 cached value (= the v7 value). Collation Notes is excluded (regenerated by the report).
- Every other cell: recalculated value vs stage 1 cached value is recorded as floating-point noise; a non-numeric
  difference, or a numeric difference > 1e-6, stops the script (it would mean the static trace missed a dependency).
"""
import sys, os, json, re, zipfile, collections
from xml.sax.saxutils import escape, unescape
import openpyxl
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from deps_v5 import downstream

ST1, LO1, SPEC, OUT, NOISE = sys.argv[1:6]
TOL = 1e-6
spec = json.load(open(SPEC))
seeds = [("Depreciation Schedule", x["cell"]) for x in spec["ds_edit"] + spec["ds_new"]] + [("PO", x["cell"]) for x in spec["po"]]
edited_f = {("Depreciation Schedule", x["cell"]) for x in spec["ds_new"] + spec["ds_edit"] if x["kind"] == "f"} | \
           {("PO", x["cell"]) for x in spec["po"] if x["new"].startswith("=")}
down, info = downstream(ST1, seeds)
down = {c for c in down if c[0] != "Collation Notes"}

z = zipfile.ZipFile(LO1)
wbx = z.read("xl/workbook.xml").decode(); rel = z.read("xl/_rels/workbook.xml.rels").decode()
sst = [unescape(re.sub(r"<[^>]+>", "", s)) for s in re.findall(r"<si>(.*?)</si>", z.read("xl/sharedStrings.xml").decode(), re.S)] \
    if "xl/sharedStrings.xml" in z.namelist() else []
raw_cache = {}


def raw(sheet, coord):
    if sheet not in raw_cache:
        nm = escape(sheet, {'"': "&quot;"})
        rid = re.search(rf'<sheet name="{re.escape(nm)}"[^>]*r:id="(rId\d+)"', wbx).group(1)
        part = "xl/" + re.search(rf'<Relationship Id="{rid}"[^>]*Target="([^"]+)"', rel).group(1)
        d = {}
        for m in re.finditer(r'<c r="([A-Z]+\d+)"([^>]*?)(?:/>|>(.*?)</c>)', z.read(part).decode(), re.S):
            body = m.group(3) or ""
            v = re.search(r"<v>([^<]*)</v>", body)
            t = re.search(r' t="(\w+)"', m.group(2))
            d[m.group(1)] = (t.group(1) if t else "n", v.group(1) if v else None)
        raw_cache[sheet] = d
    t, v = raw_cache[sheet][coord]
    if t == "s":
        return "str", escape(sst[int(v)])
    if t == "str":
        return "str", v                         # already XML-escaped text
    return t, v


a = openpyxl.load_workbook(ST1, data_only=True)
b = openpyxl.load_workbook(LO1, data_only=True)
fa = openpyxl.load_workbook(ST1)
assert a.sheetnames == b.sheetnames
isnum = lambda x: isinstance(x, (int, float)) and not isinstance(x, bool)
patches = []; noise = collections.Counter(); noise_max = 0.0; noise_ex = []; bad = []
down_same = 0
for s in a.sheetnames:
    if s == "Collation Notes":
        continue
    wa, wb_, wf = a[s], b[s], fa[s]
    mr, mc = max(wa.max_row, wb_.max_row), max(wa.max_column, wb_.max_column)
    for row in wb_.iter_rows(min_row=1, max_row=mr, max_col=mc):
        for c in row:
            key = (s, c.coordinate)
            va, vb = wa[c.coordinate].value, c.value
            fv = wf[c.coordinate].value
            is_f = isinstance(fv, str) and fv.startswith("=") or type(fv).__name__ == "ArrayFormula"
            if key in edited_f or (key in down and va != vb):
                if not is_f:
                    bad.append([s, c.coordinate, str(va), str(vb), "patch target is not a formula"]); continue
                t, v = raw(s, c.coordinate)
                if t == "n" and isnum(vb):
                    assert float(v) == float(vb), (key, v, vb)
                patches.append([s, c.coordinate, t, v])
                continue
            if va == vb:
                if key in down: down_same += 1
                continue
            if isnum(va) and isnum(vb) and abs(va - vb) <= TOL:
                noise[s] += 1; noise_max = max(noise_max, abs(va - vb))
                if len(noise_ex) < 5: noise_ex.append([s, c.coordinate, va, vb])
            else:
                bad.append([s, c.coordinate, str(va), str(vb), "change outside the edited cells and their downstream set"])
res = {"seeds": len(seeds), "trace": info, "patched": len(patches), "patched_by_sheet": dict(collections.Counter(p[0] for p in patches)),
       "downstream_total": len(down), "downstream_unchanged": down_same,
       "edited_formula_cells": len(edited_f),
       "noise_outside": {"cells": sum(noise.values()), "max_abs": noise_max, "by_sheet": dict(noise), "examples": noise_ex}, "bad": bad}
json.dump({"values": patches}, open(OUT, "w"), indent=0)
json.dump(res, open(NOISE, "w"), indent=1, default=str)
print(f"patches_v9: {len(patches)} cached values to patch {res['patched_by_sheet']}; downstream {len(down)} (unchanged {down_same}); "
      f"noise outside: {sum(noise.values())} cells, max {noise_max:.1e}; bad {len(bad)}")
if bad:
    print(bad[:10]); sys.exit(1)
